// <auto-generated />
using api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260620000100_RequireCommentStock")]
    partial class RequireCommentStock
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            MigrationModelConfiguration.ConfigureCurrent(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
