create table if not exists stocks (
    id integer generated by default as identity primary key,
    symbol varchar(32) not null,
    company_name text not null,
    purchase_price numeric(18, 2) not null default 0,
    last_dividend numeric(18, 2) not null default 0,
    industry text not null default '',
    market_cap bigint not null default 0
);

create unique index if not exists ux_stocks_symbol on stocks (symbol);

create table if not exists comments (
    id integer generated by default as identity primary key,
    title text not null,
    content text not null,
    created_on timestamptz not null default now(),
    stock_id integer not null references stocks (id) on delete cascade
);

create index if not exists ix_comments_stock_id on comments (stock_id);

create table if not exists asset_categories (
    id integer generated by default as identity primary key,
    name varchar(64) not null,
    slug varchar(64) not null,
    asset_type varchar(32) not null
);

create unique index if not exists ux_asset_categories_name on asset_categories (name);
create unique index if not exists ux_asset_categories_slug on asset_categories (slug);

create table if not exists assets (
    id integer generated by default as identity primary key,
    symbol varchar(32) not null,
    name text not null,
    asset_type varchar(32) not null,
    category_id integer null references asset_categories (id) on delete set null,
    data_provider text null,
    external_asset_id text null,
    created_on timestamptz not null default now(),
    updated_on timestamptz null
);

create unique index if not exists ux_assets_type_symbol on assets (asset_type, symbol);
create index if not exists ix_assets_category_id on assets (category_id);

create table if not exists price_history (
    id integer generated by default as identity primary key,
    asset_id integer not null references assets (id) on delete cascade,
    date date not null,
    open_price numeric(18, 4) not null,
    high_price numeric(18, 4) not null,
    low_price numeric(18, 4) not null,
    close_price numeric(18, 4) not null,
    volume bigint not null,
    source varchar(32) not null,
    source_timestamp timestamptz null,
    collected_at timestamptz not null default now(),
    raw_provider_reference jsonb null
);

create unique index if not exists ux_price_history_asset_date on price_history (asset_id, date);
create index if not exists ix_price_history_asset_date on price_history (asset_id, date desc);

create table if not exists predictions (
    id integer generated by default as identity primary key,
    asset_id varchar(64) not null,
    asset_name text not null,
    asset_type varchar(32) not null,
    category text not null,
    current_price numeric(18, 2) not null,
    predicted_price numeric(18, 2) not null,
    predicted_percent_change double precision not null,
    confidence_score double precision not null,
    risk_score double precision not null,
    bullish_score double precision not null,
    bearish_score double precision not null,
    time_horizon_days integer not null,
    model_name varchar(64) not null,
    model_version varchar(64) not null,
    is_mock boolean not null default false,
    raw_decision jsonb null,
    created_on timestamptz not null default now()
);

create index if not exists ix_predictions_asset_created_on on predictions (asset_id, created_on desc);

create table if not exists prediction_reasons (
    id integer generated by default as identity primary key,
    prediction_id integer not null references predictions (id) on delete cascade,
    kind varchar(16) not null,
    text varchar(512) not null
);

create index if not exists ix_prediction_reasons_prediction_id on prediction_reasons (prediction_id);
