-- Auth foundation for Regulas.Api. Password hashing and token creation stay in the backend;
-- frontends only receive clean auth responses and never touch these hashes directly.
create table if not exists users (
    id integer generated by default as identity primary key,
    email varchar(256) not null,
    normalized_email varchar(256) not null,
    display_name varchar(128) not null,
    password_hash text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz null,
    last_login_at timestamptz null,
    is_active boolean not null default true,
    email_confirmed boolean not null default false,
    failed_login_count integer not null default 0,
    lockout_until timestamptz null
);

create unique index if not exists ux_users_normalized_email on users (normalized_email);
create index if not exists ix_users_is_active on users (is_active);

-- Refresh tokens let MAUI and web sessions be revoked without storing raw tokens.
create table if not exists refresh_tokens (
    id integer generated by default as identity primary key,
    user_id integer not null references users (id) on delete cascade,
    token_hash text not null,
    created_at timestamptz not null default now(),
    expires_at timestamptz not null,
    revoked_at timestamptz null,
    replaced_by_token_hash text null,
    created_by_ip varchar(64) null,
    revoked_by_ip varchar(64) null
);

create unique index if not exists ux_refresh_tokens_token_hash on refresh_tokens (token_hash);
create index if not exists ix_refresh_tokens_user_id on refresh_tokens (user_id);
create index if not exists ix_refresh_tokens_expires_at on refresh_tokens (expires_at);

-- Small per-user settings row for app preferences before advanced profile work exists.
create table if not exists user_settings (
    user_id integer primary key references users (id) on delete cascade,
    settings_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz null
);
