create table if not exists background_job_runs (
    id integer generated by default as identity primary key,
    job_name varchar(64) not null,
    status varchar(32) not null,
    detail text null,
    items_processed integer not null default 0,
    started_at timestamptz not null default now(),
    finished_at timestamptz null
);

create index if not exists ix_background_job_runs_job_started
    on background_job_runs (job_name, started_at desc);
