-- Durable ledger of real trained artifacts. Promotion eligibility records the
-- trainer's honest holdout comparison; activating an eligible version is a
-- separate deployment concern.
create table if not exists trained_model_versions (
    id integer generated by default as identity primary key,
    model_name varchar(64) not null check (length(btrim(model_name)) between 1 and 64),
    model_version varchar(64) not null check (length(btrim(model_version)) between 1 and 64),
    category varchar(64) not null check (length(btrim(category)) between 1 and 64),
    contract_version varchar(32) not null check (length(btrim(contract_version)) between 1 and 32),
    series_count integer not null check (series_count > 0),
    artifact_json text not null check (octet_length(artifact_json) between 2 and 262144),
    metrics_json text not null check (octet_length(metrics_json) between 2 and 65536),
    promotion_eligible boolean not null default false,
    created_at timestamptz not null default now()
);

create index if not exists ix_trained_model_versions_model
    on trained_model_versions (model_name, created_at desc);
create index if not exists ix_trained_model_versions_eligible
    on trained_model_versions (promotion_eligible, created_at desc);
